<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>StackManager</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Publicize Include="Assembly-CSharp" IncludeVirtualMembers="true" IncludeCompilerGeneratedMembers="true" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Rust.Harmony">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Global">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Rust.Global.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Localization">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Rust.Localization.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Facepunch.Console.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\Unity.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>D:\!RustServer\RustDedicated_Data\Managed\System.Net.Http.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0GrimmCUI"><HintPath>..\..\..\HarmonyMods\0GrimmCUI.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup><Compile Remove="Patches\Cui_Endtest_Patch.cs" /><Compile Remove="UIFramework\**" /><Compile Remove="Pooling\**" /><Compile Remove="Json\**" /></ItemGroup>
</Project>
