<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GrimmNPC2</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Rust.Harmony">
      <HintPath>$(RustManagedDir)Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(RustManagedDir)0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RustManagedDir)Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(RustManagedDir)Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>$(RustManagedDir)Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>$(RustManagedDir)Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>$(RustManagedDir)Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>$(RustManagedDir)Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(RustManagedDir)Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RustManagedDir)UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(RustManagedDir)UnityEngine.AIModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
