<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SafeZonePVE</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ManagedPath Condition="'$(ManagedPath)' == ''">$(MSBuildProjectDirectory)\..\..\..\RustDedicated_Data\Managed</ManagedPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Rust.Harmony">
      <HintPath>$(ManagedPath)\Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedPath)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(ManagedPath)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>$(ManagedPath)\Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>$(ManagedPath)\Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>$(ManagedPath)\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>$(ManagedPath)\Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>
