<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BuriedItemsFix</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Rust.Harmony">
      <HintPath>$(RustManaged)\Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(RustManaged)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RustManaged)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>$(RustManaged)\Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>$(RustManaged)\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RustManaged)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
