<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Rustcord</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>Rustcord</RootNamespace>
    <Description>Harmony mod: Rustcord - game server monitoring through Discord. No Oxide. Uses webhooks for Game->Discord. Compatible with ticket-support-system-discord relay.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Rust.Harmony">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Facepunch.Console.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Global">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\Rust.Global.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>C:\!2XRUST\RustDedicated_Data\Managed\System.Net.Http.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
