/***********************************************************************************************************************/
/*** DO NOT edit this file! Edit the files under `oxide/config` and/or `oxide/lang`, created once plugin has loaded. ***/
/*** Please note, support cannot be provided if the plugin has been modified. Please use a fresh copy if modified.   ***/
/***********************************************************************************************************************/

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using Oxide.Core;
using Oxide.Core.Plugins;
using Oxide.Game.Rust.Cui;
using UnityEngine;
using Rust;
using Random = UnityEngine.Random;
using System.Net;
using System.IO;
using Facepunch;

namespace Oxide.Plugins
{
    [Info("Rocket Guidance System", "MACHIN3 edited by Grimm530", "1.0.704")]
    [Description("Adds Rocket Guidance System that allows rocket launcher to lock on targets.")]
    public partial class RocketGuidanceSystem : RustPlugin
    {
        #region Update Log
        /*****************************************************
        【 𝓜𝓐𝓒𝓗𝓘𝓝𝓔 】
        Website: https://www.rustlevels.com/XPerience/
        Discord: http://discord.rustlevels.com/
        /****************************************************
 
        --------------------
        Version 1.0.703
        --------------------

        ✯ Added RidableHorse changes
        
        //*****************************************************/
        
        #region PastUpdates
        /*
        --------------------
        Version 1.0.700
        --------------------

        ✯ Added support for the Dragon Rocket Launcher

        --------------------
        Version 1.0.600
        --------------------

        ✯ Fixed UI issues
        ✯ Fixed Rockets not locking due to UI issues

        --------------------
        Version 1.0.500
        --------------------

        ✯ Fix for latest Rust update
        ✯ Fixed inc rockets not locking unless all rockets enabled

        --------------------
        Version 1.0.400
        --------------------

        ✯ Fixed rockets not being able to track Patrol Helicopter

        --------------------
        Version 1.0.300
        --------------------

        ✯ Fix for Rust update - Sept 7th

        --------------------
        Version 1.0.200
        --------------------

        ✯ Added option to set damage amount per target entity type
        ✯ Added permissions to use RGS
        ✯ Fixed unload issues not clearing RocketGuidanceSystem data
        ✯ Fixed max distance settings not applying

        --------------------
        Version 1.0.100
        --------------------

        ✯ Removed unused statements
        ✯ Fixed unload issues not removing players from cache
        
        --------------------
        Version 1.0.000
        --------------------

        ✯ Created the Rocket Guidance System using the Demolition feature from the XPerience Addon
        */
        #endregion

        //*****************************************************/
        #endregion

        #region Refrences
        [PluginReference]
        private readonly Plugin XPerienceAddon, CombatClasses;
        #endregion

        #region Fields
        private Configuration config;
        private static RocketGuidanceSystem Instance { get; set; }
        private bool _isRGReady;
        private bool _isRestart = true;
        private Dictionary<string, uint> _RGImageList;
        private const string RGSPerm = "rocketguidancesystem.use";
        #endregion

        #region Config
        private class Configuration : SerializableConfiguration
        {
            [JsonProperty("Rocket Targets")]
            public RocketTargets rockettargets = new RocketTargets();
            [JsonProperty("Rocket Ammo")]
            public RocketAmmo rocketammo = new RocketAmmo();
            [JsonProperty("Rocket Settings")]
            public RocketSettings rocketsettings = new RocketSettings();
        }
        public class RocketTargets
        {
            public bool players = true;
            public bool npcs = true;
            public bool animals = true;
            public bool bradleyapc = true;
            public bool patrolheli = true;
            public bool ch47 = true;
            public bool turrets = true;
            public bool buildings = true;
            public bool minicopter = true;
            public bool hotairballoon = true;
            public bool drones = true;
            public bool boats = true;
            public bool vehicles = true;
            public bool trains = true;
            public bool planes = true;
            public bool authbuildings = false;
            public Dictionary<int, EntityList> entityList = new Dictionary<int, EntityList>
            {
                [0] = new EntityList
                {
                    entity = "chicken",
                    name = "Chicken",
                },
                [1] = new EntityList
                {
                    entity = "boar",
                    name = "Boar",
                },
                [2] = new EntityList
                {
                    entity = "stag",
                    name = "Stag",
                },
                [3] = new EntityList
                {
                    entity = "wolf2",
                    name = "Wolf2",
                },
                [4] = new EntityList
                {
                    entity = "bear",
                    name = "Bear",
                },
                [5] = new EntityList
                {
                    entity = "polarbear",
                    name = "Polar Bear",
                },
                [6] = new EntityList
                {
                    entity = "simpleshark",
                    name = "Shark",
                },
                [7] = new EntityList
                {
                    entity = "ridablehorse",
                    name = "Horse",
                },
                [8] = new EntityList
                {
                    entity = "scientistnpc",
                    name = "Scientist",
                },
                [9] = new EntityList
                {
                    entity = "tunneldweller",
                    name = "Tunnel Dweller",
                },
                [10] = new EntityList
                {
                    entity = "underwaterdweller",
                    name = "Underwater Dweller",
                },
                [11] = new EntityList
                {
                    entity = "scarecrownpc",
                    name = "Scarecrow",
                },
                [12] = new EntityList
                {
                    entity = "zombienpc",
                    name = "Zombie",
                },
                [13] = new EntityList
                {
                    entity = "customscientistnpc",
                    name = "Custom Scientist",
                },
                [14] = new EntityList
                {
                    entity = "bradleyapc",
                    name = "Bradley APC",
                },
                [15] = new EntityList
                {
                    entity = "patrolhelicopter",
                    name = "Patrol Helicopter",
                },
                [16] = new EntityList
                {
                    entity = "basehelicopter",
                    name = "Patrol Helicopter",
                },
                [17] = new EntityList
                {
                    entity = "tugboat",
                    name = "Tug Boat",
                },
            };
        }
        public class RocketAmmo
        {
            public bool basicrocket = true;
            public bool smokerocket = true;
            public bool hvrocket = true;
            public bool incrocket = true;
        }
        public class RocketSettings
        {
            public double chance = 75;
            public int timetolock = 5;
            public float speed = .20f;
            public float detonate = 20;
            public int basedamage = 100;
            public double distance = 150;
            public int playerdamage = 100;
            public int npcdamage = 100;
            public int animaldamage = 100;
            public int bradleyapcdamage = 100;
            public int patrolhelidamage = 100;
            public int ch47damage = 100;
            public int turretdamage = 100;
            public int buildingdamage = 100;
            public int minicopterdamage = 100;
            public int hotairballoondamage = 100;
            public int dronesdamage = 100;
            public int boatdamage = 100;
            public int vehicledamage = 100;
            public int traindamage = 100;
            public int planedamage = 100;
            public bool reqlock = true;
            public bool useCombatClasses = false;
            public string CombatClass = "demolition";
            [JsonProperty("debuglog")]
            public bool debug = false;
        }
        public class EntityList
        {
            public string entity = "";
            public string name = "";
        }
        protected override void LoadDefaultConfig() => config = new Configuration();
        protected override void LoadConfig()
        {
            base.LoadConfig();
            try
            {
                config = Config.ReadObject<Configuration>();
                if (config == null)
                {
                    throw new JsonException();
                }
                if (MaybeUpdateConfig(config))
                {
                    PrintWarning("Configuration appears to be outdated; updating and saving");
                    SaveConfig();
                }
            }
            catch
            {
                PrintWarning($"Configuration file {Name}.json is invalid; using defaults");
                LoadDefaultConfig();
            }
        }
        protected override void SaveConfig()
        {
            PrintWarning($"Configuration changes saved to {Name}.json");
            Config.WriteObject(config, true);
        }
        #region UpdateChecker
        internal class SerializableConfiguration
        {
            public string ToJson() => JsonConvert.SerializeObject(this);

            public Dictionary<string, object> ToDictionary() => JsonHelper.Deserialize(ToJson()) as Dictionary<string, object>;
        }
        private static class JsonHelper
        {
            public static object Deserialize(string json) => ToObject(JToken.Parse(json));

            private static object ToObject(JToken token)
            {
                switch (token.Type)
                {
                    case JTokenType.Object:
                        return token.Children<JProperty>().ToDictionary(prop => prop.Name, prop => ToObject(prop.Value));
                    case JTokenType.Array:
                        return token.Select(ToObject).ToList();

                    default:
                        return ((JValue)token).Value;
                }
            }
        }
        private bool MaybeUpdateConfig(SerializableConfiguration config)
        {
            var currentWithDefaults = config.ToDictionary();
            var currentRaw = Config.ToDictionary(x => x.Key, x => x.Value);
            return MaybeUpdateConfigDict(currentWithDefaults, currentRaw);
        }
        private bool MaybeUpdateConfigDict(Dictionary<string, object> currentWithDefaults, Dictionary<string, object> currentRaw)
        {
            bool changed = false;

            foreach (var key in currentWithDefaults.Keys)
            {
                object currentRawValue;
                if (currentRaw.TryGetValue(key, out currentRawValue))
                {
                    var defaultDictValue = currentWithDefaults[key] as Dictionary<string, object>;
                    var currentDictValue = currentRawValue as Dictionary<string, object>;

                    if (defaultDictValue != null)
                    {
                        if (currentDictValue == null)
                        {
                            currentRaw[key] = currentWithDefaults[key];
                            changed = true;
                        }
                        else if (MaybeUpdateConfigDict(defaultDictValue, currentDictValue))
                            changed = true;
                    }
                }
                else
                {
                    currentRaw[key] = currentWithDefaults[key];
                    changed = true;
                }
            }

            return changed;
        }
        #endregion
        #endregion

        #region Hooks
        private void OnServerInitialized()
        {
            permission.RegisterPermission(RGSPerm, this);
            LoadImages();
            BasePlayer.activePlayerList.ToList().ForEach(OnPlayerConnected);
        }
        private void Loaded()
        {
            Instance = this;
            if(XPerienceAddon != null)
            {
                Puts("WARNING! XPerience Addon detected. Disable rocket abilities in the XPerience Addon to prevent conflicts!");
            }
        }
        private void Unload()
        {
            var guidancesystemPlayersToDestroy = new List<GuidanceSystemPlayer>();
            foreach (var entity in BaseNetworkable.serverEntities)
            {
                if (entity != null && !entity.IsDestroyed)
                {
                    var player = entity.GetComponent<GuidanceSystemPlayer>();
                    if (player != null)
                    {
                        guidancesystemPlayersToDestroy.Add(player);
                    }
                }
            }
            foreach (var player in guidancesystemPlayersToDestroy)
            {
                UnityEngine.Object.Destroy(player);
            }

            var rocketsToDestroy = new List<GuidanceSystem>();
            foreach (var entity in BaseNetworkable.serverEntities)
            {
                if (entity != null && !entity.IsDestroyed)
                {
                    var rocket = entity.GetComponent<GuidanceSystem>();
                    if (rocket != null)
                    {
                        rocketsToDestroy.Add(rocket);
                    }
                }
            }
            foreach (var rocket in rocketsToDestroy)
            {
                UnityEngine.Object.Destroy(rocket);
            }
        }
        private void OnPlayerConnected(BasePlayer player)
        {
            if (player == null || !player.userID.Get().IsSteamId() || player.IsNpc) return;
            if (GetPlayer(player) == null)
            {
                DebugLog($"OnPlayerConnected - Adding GuidanceSystemPlayer component to {player.displayName} ({player.UserIDString})");
                player.gameObject.AddComponent<GuidanceSystemPlayer>();
            }
            else
            {
                DebugLog($"OnPlayerConnected - Player {player.displayName} already has GuidanceSystemPlayer component");
            }
        }
        
        // Hook to detect when player equips/unequips items - optimize tracking activation
        private void OnItemHeld(Item item, BasePlayer player)
        {
            if (player == null || !player.userID.Get().IsSteamId() || player.IsNpc) return;
            
            var guidanceComponent = GetPlayer(player);
            if (guidanceComponent == null) return;
            
            // Check if the held item is a rocket launcher (by item ID or type)
            BaseProjectile baseProjectile = item?.GetHeldEntity() as BaseProjectile;
            bool isRocketLauncher = item != null && (
                item.info.itemid == 442886268 || 
                item.info.itemid == -1315992997 || 
                item.info.itemid == 494161326 ||
                baseProjectile is RPGLauncher
            );
            
            if (isRocketLauncher)
            {
                DebugLog($"Player {player.displayName} ({player.UserIDString}) EQUIPPED rocket launcher (ItemID: {item.info.itemid})");
            }
            else if (item != null)
            {
                DebugLog($"Player {player.displayName} ({player.UserIDString}) EQUIPPED other item: {item.info.displayName.english} (ItemID: {item.info.itemid})");
            }
            else
            {
                DebugLog($"Player {player.displayName} ({player.UserIDString}) UNEQUIPPED item (item is null)");
            }
            
            // Update the equipped status in the component
            guidanceComponent.hasRocketLauncherEquipped = isRocketLauncher;
            
            // If not a rocket launcher and tracking is active, stop it
            if (!isRocketLauncher && guidanceComponent.isTrackingActive)
            {
                DebugLog($"Player {player.displayName} - Deactivating tracking (not rocket launcher)");
                guidanceComponent.StopTargetLock(false);
                guidanceComponent.isTrackingActive = false;
            }
            // If it is a rocket launcher, the Update() method will handle activation when aiming starts
        }
        private void OnPlayerDisconnected(BasePlayer player)
        {
            // Destroy all UI elements
            if (player?.net != null)
            {
                CuiHelper.DestroyUi(player, RGTargetDisplay);
                CuiHelper.DestroyUi(player, "RGCenterCrosshair");
                CuiHelper.DestroyUi(player, "RGCornerTL");
                CuiHelper.DestroyUi(player, "RGCornerTR");
                CuiHelper.DestroyUi(player, "RGCornerBL");
                CuiHelper.DestroyUi(player, "RGCornerBR");
                CuiHelper.DestroyUi(player, "RGStatusPanel");
                CuiHelper.DestroyUi(player, "RGStatusText");
                CuiHelper.DestroyUi(player, "RGInfoPanel");
                CuiHelper.DestroyUi(player, "RGTargetName");
                CuiHelper.DestroyUi(player, "RGDistance");
                
                // Also destroy via CommunityEntity RPC
                var communityEntity = CommunityEntity.ServerInstance;
                if (communityEntity != null)
                {
                    var destroyData = Pool.Get<List<object>>();
                    destroyData.Add(new { destroyUi = "RGCenterCrosshair" });
                    destroyData.Add(new { destroyUi = "RGCornerTL" });
                    destroyData.Add(new { destroyUi = "RGCornerTR" });
                    destroyData.Add(new { destroyUi = "RGCornerBL" });
                    destroyData.Add(new { destroyUi = "RGCornerBR" });
                    destroyData.Add(new { destroyUi = "RGStatusPanel" });
                    destroyData.Add(new { destroyUi = "RGInfoPanel" });
                    communityEntity.ClientRPC(RpcTarget.Player("AddUI", player.net.connection), JsonConvert.SerializeObject(destroyData));
                    Pool.FreeUnmanaged(ref destroyData);
                }
            }
            
            GuidanceSystemPlayer guidancesystemPlayer = GetPlayer(player);
            if (guidancesystemPlayer != null)
            {
                UnityEngine.Object.Destroy(guidancesystemPlayer);
            }
        }
        private void OnRocketLaunched(BasePlayer player, BaseEntity entity)
        {
            if (player == null) return;
            GuidanceSystemPlayer guidancesystemPlayer = GetPlayer(player);
            if (guidancesystemPlayer == null) return;
            if (!guidancesystemPlayer.TargetLocked) return;

            // Adjust speed and gravity
            ServerProjectile serverProjectile = entity.GetComponent<ServerProjectile>();
            if (serverProjectile == null) return;

            serverProjectile.gravityModifier = 0f;
            serverProjectile.speed += serverProjectile.speed * config.rocketsettings.speed;

            // Adjust damage
            TimedExplosive timedExplosive = entity.GetComponent<TimedExplosive>();
            if (timedExplosive == null) return;

            foreach (DamageTypeEntry damageType in timedExplosive.damageTypes)
            {
                int amount = GetDamageAmount(entity);
                damageType.amount += (float)amount;
            }

            // Set fuse and explosion effect
            timedExplosive.SetFuse(config.rocketsettings.detonate);
            timedExplosive.explosionEffect.guid = string.Empty;

            // Initialize guidance system
            GuidanceSystem rocket = entity.gameObject.AddComponent<GuidanceSystem>();
            rocket.Initialize(guidancesystemPlayer.Target, player);
            guidancesystemPlayer.StopTargetLock(false);
        }
        #endregion

        #region Helpers
        private void DebugLog(string message)
        {
            if (config?.rocketsettings?.debug == true)
            {
                PrintWarning($"[RGS DEBUG] {message}");
            }
        }
        private static BasePlayer FindPlayer(ulong playerid)
        {
            foreach (var player in BasePlayer.allPlayerList)
            {
                if (player.userID == playerid)
                    return player;
            }
            return null;
        }
        private GuidanceSystemPlayer GetPlayer(BasePlayer player) => player?.GetComponent<GuidanceSystemPlayer>();
        private string GetTargeName(BaseEntity target)
        {
            var targetname = target.ToPlayer()?.displayName;
            if (target is BasePlayer && target.ToPlayer().userID.Get().IsSteamId())
            {
                return target.ToPlayer().displayName;
            }
            else if (!string.IsNullOrEmpty(targetname) && targetname != target.ToPlayer()?.userID.ToString())
            {
                return targetname;
            }
            else if (string.IsNullOrEmpty(targetname) && (target is BuildingBlock || target is SimpleBuildingBlock))
            {
                return "Building";
            }
            else if (string.IsNullOrEmpty(targetname) && (target is TrainEngine || target is TrainCar))
            {
                return "Train";
            }
            else if (string.IsNullOrEmpty(targetname) && (target is ModularCar || target is BaseVehicleModule || target is BasicCar))
            {
                return "Vehicle";
            }
            else if (string.IsNullOrEmpty(targetname) && (target is AutoTurret || target is FlameTurret || target is GunTrap))
            {
                return "Turret";
            }
            else if (string.IsNullOrEmpty(targetname) && target is BaseBoat)
            {
                return "Boat";
            }
            else if (string.IsNullOrEmpty(targetname) && target is HotAirBalloon)
            {
                return "Hot Air Balloon";
            }
            else if (string.IsNullOrEmpty(targetname) && target is CH47Helicopter)
            {
                return "CH47 Helicopter";
            }
            else if (string.IsNullOrEmpty(targetname) && target is ScrapTransportHelicopter)
            {
                return "Scrap Transport Helicopter";
            }
            else if (string.IsNullOrEmpty(targetname) && target is Minicopter)
            {
                return "MiniCopter";
            }
            else if (string.IsNullOrEmpty(targetname) && target is Drone && (target as Drone).IsBeingControlled)
            {
                return "Drone";
            }
            else if (string.IsNullOrEmpty(targetname))
            {
                foreach (var getentity in config.rockettargets.entityList)
                {
                    if (getentity.Value.entity == target?.GetType().Name.ToLower())
                    {
                        return getentity.Value.name;
                    }
                }
            }
            return "unkown";
        }
        private int GetDamageAmount(BaseEntity target)
        {
            if (target is BasePlayer)
            {
                return config.rocketsettings.playerdamage;
            }
            else if (target is BuildingBlock || target is SimpleBuildingBlock)
            {
                return config.rocketsettings.buildingdamage;
            }
            else if (target is TrainEngine || target is TrainCar)
            {
                return config.rocketsettings.traindamage;
            }
            else if (target is ModularCar || target is BaseVehicleModule || target is BasicCar)
            {
                return config.rocketsettings.vehicledamage;
            }
            else if (target is AutoTurret || target is FlameTurret || target is GunTrap)
            {
                return config.rocketsettings.turretdamage;
            }
            else if (target is BaseBoat)
            {
                return config.rocketsettings.boatdamage;
            }
            else if (target is HotAirBalloon)
            {
                return config.rocketsettings.hotairballoondamage;
            }
            else if (target is CH47Helicopter)
            {
                return config.rocketsettings.ch47damage;
            }
            else if (target is ScrapTransportHelicopter)
            {
                return config.rocketsettings.ch47damage;
            }
            else if (target is Minicopter)
            {
                return config.rocketsettings.minicopterdamage;
            }
            else if (target is Drone && (target as Drone).IsBeingControlled)
            {
                return config.rocketsettings.dronesdamage;
            }
            return config.rocketsettings.basedamage;
        }
        private class GuidanceSystemPlayer : MonoBehaviour
        {
            private BasePlayer player;
            private RaycastHit raycastHit;
            private BaseEntity lastTarget;
            private Vector3 targetLocation;
            private float timeLocked;
            private bool isAlert;
            private bool isLocked;
            private float UpdateTargetDisplay;
            // Cache UI state to avoid unnecessary updates
            private string lastTargetName = "";
            private string lastDistance = "";
            private bool lastIsLocked = false;
            private bool lastLockFailed = false;
            private bool uiActive = false;
            public bool TargetLocked => isLocked;
            public BaseEntity Target => lastTarget;
            public float GetTimeLocked() => timeLocked;
            internal bool hasRocketLauncherEquipped = false;
            
            internal bool isTrackingActive = false; // Track if we're actively tracking (not just enabled)
            private bool chancePassedForCurrentTarget = false; // Track if chance check passed for current target
            private BaseEntity targetForChanceCheck = null; // Track which target we checked chance for
            
            private void Awake()
            {
                player = GetComponent<BasePlayer>();
                // Component stays enabled so Update() runs, but we control activity with isTrackingActive
                enabled = true;
                isTrackingActive = false;
                Instance.DebugLog($"GuidanceSystemPlayer component AWAKE for player: {player?.displayName} ({player?.UserIDString})");
            }
            
            private void Update()
            {
                // Early exit if player is invalid
                if (!player || player.IsDead() || !player.userID.Get().IsSteamId())
                {
                    if (isTrackingActive)
                    {
                        StopTargetLock(false);
                        isTrackingActive = false;
                    }
                    return;
                }
                
                // Check equipped item (lightweight check every frame, but very fast)
                Item activeItem = player.GetActiveItem();
                BaseProjectile activeProjectile = activeItem?.GetHeldEntity() as BaseProjectile;
                bool currentlyHasRocketLauncher = activeItem != null && (
                    activeItem.info.itemid == 442886268 || 
                    activeItem.info.itemid == -1315992997 ||
                    activeItem.info.itemid == 494161326 ||
                    activeProjectile is RPGLauncher
                );
                
                if (hasRocketLauncherEquipped != currentlyHasRocketLauncher)
                {
                    hasRocketLauncherEquipped = currentlyHasRocketLauncher;
                    if (hasRocketLauncherEquipped)
                    {
                        Instance.DebugLog($"Player {player.displayName} - Rocket launcher EQUIPPED (ItemID: {activeItem.info.itemid})");
                    }
                    else
                    {
                        Instance.DebugLog($"Player {player.displayName} - Rocket launcher UNEQUIPPED");
                        if (isTrackingActive)
                        {
                            StopTargetLock(false);
                            isTrackingActive = false;
                        }
                        return;
                    }
                }
                
                // If no rocket launcher, exit early
                if (!hasRocketLauncherEquipped)
                {
                    if (isTrackingActive)
                    {
                        StopTargetLock(false);
                        isTrackingActive = false;
                    }
                    return;
                }
                
                // Check permission (only when rocket launcher is equipped)
                if (!Instance.permission.UserHasPermission(player.UserIDString, RGSPerm))
                {
                    if (isTrackingActive)
                    {
                        StopTargetLock(false);
                        isTrackingActive = false;
                    }
                    return;
                }
                
                // Check if player is aiming
                bool isAiming = player.serverInput.IsDown(BUTTON.FIRE_SECONDARY) && HasRocketLauncher();
                
                if (isAiming)
                {
                    if (!isTrackingActive)
                    {
                        Instance.DebugLog($"Player {player.displayName} - TRACKING ACTIVATED (started aiming with rocket launcher)");
                        isTrackingActive = true;
                    }
                    
                    // Start tracking - chance will be checked inside StartTargetLock when new target is detected
                    // For existing targets, use the stored chance result
                    // Run every frame like original for better responsiveness
                    StartTargetLock();
                }
                else
                {
                    // Not aiming - destroy UI and stop tracking
                    if (isTrackingActive)
                    {
                        Instance.DebugLog($"Player {player.displayName} - TRACKING DEACTIVATED (stopped aiming)");
                        StopTargetLock(false);
                        isTrackingActive = false;
                        // Force UI destruction
                        CuiHelper.DestroyUi(player, RGTargetDisplay);
                        CuiHelper.DestroyUi(player, "RGCenterCrosshair");
                        CuiHelper.DestroyUi(player, "RGStatusPanel");
                        CuiHelper.DestroyUi(player, "RGStatusText");
                        CuiHelper.DestroyUi(player, "RGInfoPanel");
                        CuiHelper.DestroyUi(player, "RGTargetName");
                        CuiHelper.DestroyUi(player, "RGDistance");
                    }
                }
            }
            private void Alert()
            {
                isAlert = true;
                // Play sound at player's center position for consistent volume - use transform.position which is more stable
                Effect.server.Run("assets/prefabs/locks/keypad/effects/lock.code.unlock.prefab", player.transform.position);
                InvokeHandler.Invoke(this, Alert, TargetLocked ? 0.1f : 1f);
            }
            private bool HasRocketLauncher()
            {
                if (player == null) return false;
                Item item = player.GetActiveItem();
                if (item == null) return false;
                
                // Check for Rocket Launcher, Dragon Rocket Launcher, or RPG Launcher by item ID or type
                BaseProjectile baseProjectile = item.GetHeldEntity() as BaseProjectile;
                if (baseProjectile == null) return false;
                
                // Check if it's a rocket launcher by item ID or by type (RPGLauncher extends BaseLauncher)
                bool isRocketLauncher = item.info.itemid == 442886268 || item.info.itemid == -1315992997 || item.info.itemid == 494161326;
                bool isRPGLauncher = baseProjectile is RPGLauncher;
                
                if (!isRocketLauncher && !isRPGLauncher) return false;
                if (!HasTargetableAmmo(baseProjectile)) return false;
                if (baseProjectile.primaryMagazine.contents > 0) return true;
                return false;
            }
            private bool HasTargetableAmmo(BaseProjectile baseProjectile)
            {
                if (baseProjectile == null) return false;
                switch (baseProjectile.primaryMagazine.ammoType.itemid)
                {
                    case -742865266:
                        if (Instance.config.rocketammo.basicrocket)
                        {
                            return true;
                        }
                        break;
                    case -17123659:
                        if (Instance.config.rocketammo.smokerocket)
                        {
                            return true;
                        }
                        break;
                    case -1841918730:
                        if (Instance.config.rocketammo.hvrocket)
                        {
                            return true;
                        }
                        break;
                    case 1638322904:
                        if (Instance.config.rocketammo.incrocket)
                        {
                            return true;
                        }
                        break;
                }
                /*
                if (Instance.config.rocketammo.basicrocket && baseProjectile.primaryMagazine.ammoType.itemid == -742865266)
                {
                    return true;
                }
                if (Instance.config.rocketammo.smokerocket && baseProjectile.primaryMagazine.ammoType.itemid == -17123659)
                {
                    return true;
                }
                if (Instance.config.rocketammo.hvrocket && baseProjectile.primaryMagazine.ammoType.itemid == -1841918730)
                {
                    return true;
                }
                if (Instance.config.rocketammo.incrocket && baseProjectile.primaryMagazine.ammoType.itemid == 1638322904)
                {
                    return true;
                }
                */
                return false;
            }
            private bool TargetList(BaseEntity entity)
            {
                if (entity == null) return false;
                bool cantarget = false;
                if (entity is BasePlayer)
                {
                    if ((entity as BasePlayer).IsNpc)
                    {
                        cantarget = Instance.config.rockettargets.npcs;
                        return cantarget;
                    }
                    else
                    {
                        cantarget = Instance.config.rockettargets.players;
                        return cantarget;
                    }
                }
                else if (entity is BaseNpc || entity is RidableHorse)
                {
                    cantarget = Instance.config.rockettargets.animals;
                    return cantarget;
                }
                else if (entity is AutoTurret || entity is FlameTurret || entity is GunTrap)
                {
                    cantarget = Instance.config.rockettargets.turrets;
                    return cantarget;
                }
                else if (entity is BradleyAPC)
                {
                    cantarget = Instance.config.rockettargets.bradleyapc;
                    return cantarget;
                }
                else if (entity is PatrolHelicopter)
                {
                    cantarget = Instance.config.rockettargets.patrolheli;
                    return cantarget;
                }
                else if (entity is ScrapTransportHelicopter)
                {
                    cantarget = Instance.config.rockettargets.ch47;
                    return cantarget;
                }
                else if (entity is Minicopter)
                {
                    cantarget = Instance.config.rockettargets.minicopter;
                    return cantarget;
                }
                else if (entity is CH47Helicopter)
                {
                    cantarget = Instance.config.rockettargets.ch47;
                    return cantarget;
                }
                else if (entity is BaseHelicopter)
                {
                    cantarget = Instance.config.rockettargets.patrolheli;
                    return cantarget;
                }
                else if (entity is HotAirBalloon)
                {
                    cantarget = Instance.config.rockettargets.hotairballoon;
                    return cantarget;
                }
                else if (entity is Drone && (entity as Drone).IsBeingControlled)
                {
                    cantarget = Instance.config.rockettargets.drones;
                    return cantarget;
                }
                else if (entity is BasicCar || entity is ModularCar || entity is BaseVehicleModule)
                {
                    cantarget = Instance.config.rockettargets.vehicles;
                    return cantarget;
                }
                else if (entity is BaseBoat)
                {
                    cantarget = Instance.config.rockettargets.boats;
                    return cantarget;
                }
                else if (entity is TrainEngine)
                {
                    cantarget = Instance.config.rockettargets.trains;
                    return cantarget;
                }
                else if (entity is TrainCar)
                {
                    cantarget = Instance.config.rockettargets.trains;
                    return cantarget;
                }
                else if (entity is BuildingPrivlidge)
                {
                    return cantarget;
                }
                else if (entity is BuildingBlock || entity is SimpleBuildingBlock)
                {
                    cantarget = Instance.config.rockettargets.buildings;
                    bool cantargetauth = Instance.config.rockettargets.authbuildings;
                    BuildingPrivlidge getbuilding = entity.GetBuildingPrivilege();
                    if (!cantargetauth && getbuilding != null && getbuilding.IsAuthed(player)) return false;
                    return cantarget;
                }
                else if (entity.ShortPrefabName.Equals("cargo_plane", System.StringComparison.OrdinalIgnoreCase))
                {
                    cantarget = Instance.config.rockettargets.planes;
                    return cantarget;
                }
                return cantarget;
            }
            private void StartTargetLock(bool failed = false)
            {
                if (lastTarget && !lastTarget.IsDestroyed)
                {
                    float angle = Vector3.Angle(player.eyes.HeadForward(), lastTarget.transform.TransformPoint(targetLocation) - player.eyes.position);
                    // Increased angle tolerance from 5.5° to 10° for less sensitivity
                    if (angle <= 10f)
                    {
                        if (GamePhysics.LineOfSight(player.eyes.position + player.eyes.HeadForward(), lastTarget.transform.TransformPoint(targetLocation), ~(1 << 3 | 1 << 10 | 1 << 18 | 1 << 28 | 1 << 29), 0.5f))
                        {
                            // Use stored chance result for existing target (don't re-check)
                            bool shouldFail = !chancePassedForCurrentTarget;
                            TargetUpdate(shouldFail);
                            return;
                        }
                    }
                }
                // Increased SphereCast radius from 0.25f to 0.75f for larger hitbox (less sensitive)
                if (Physics.SphereCast(player.eyes.HeadRay(), 0.75f, out raycastHit, 2000, ~(1 << 3 | 1 << 10 | 1 << 18 | 1 << 28 | 1 << 29), QueryTriggerInteraction.Collide))
                {
                    BaseEntity hitEntity = raycastHit.GetEntity();
                    if (hitEntity)
                    {
                        if (hitEntity != lastTarget)
                        {
                            if (TargetList(hitEntity))
                            {
                                Instance.DebugLog($"Player {player.displayName} - NEW TARGET DETECTED: {hitEntity.ShortPrefabName} (Type: {hitEntity.GetType().Name})");
                                
                                // Reset timer when switching targets (or initializing for first target)
                                timeLocked = 0;
                                isLocked = false;
                                
                                lastTarget = hitEntity;
                                targetLocation = lastTarget.transform.InverseTransformPoint(raycastHit.point);
                                
                                // Check chance ONCE when new target is acquired
                                double chance = Instance.config.rocketsettings.chance;
                                chancePassedForCurrentTarget = (Random.Range(1, 101) <= chance);
                                targetForChanceCheck = hitEntity;
                                Instance.DebugLog($"Player {player.displayName} - Chance check for new target: {(chancePassedForCurrentTarget ? "PASSED" : "FAILED")} (chance: {chance}%)");
                                
                                // Start tracking the new target immediately
                                bool newTargetShouldFail = !chancePassedForCurrentTarget;
                                TargetUpdate(newTargetShouldFail);
                                return;
                            }
                            else
                            {
                                Instance.DebugLog($"Player {player.displayName} - Hit entity {hitEntity.ShortPrefabName} but not in target list");
                                StopTargetLock(true);
                                return;
                            }
                        }
                        Instance.DebugLog($"Player {player.displayName} - Tracking same target: {hitEntity.ShortPrefabName}");
                        // Use stored chance result for same target (don't re-check)
                        bool shouldFail = !chancePassedForCurrentTarget;
                        TargetUpdate(shouldFail);
                        return;
                    }
                }
                Instance.DebugLog($"Player {player.displayName} - No target detected in raycast");
                StopTargetLock(false);
            }
            private void TargetUpdate(bool failed = false)
            {
                float rocketlock = Instance.config.rocketsettings.timetolock;
                float maxdistance = (float)Instance.config.rocketsettings.distance;
                if (!isAlert) Alert();
                timeLocked += Time.deltaTime;
                isLocked = timeLocked >= rocketlock;
                if (failed)
                {
                    isLocked = false;
                }
                if (Time.time > UpdateTargetDisplay)
                {
                    UpdateTargetDisplay = Time.time + 0.25f; // Update UI every 0.25s (original timing for better visual flash)
                    var shortname = Instance.GetTargeName(Target);
                    float targetDistance = Target ? Vector3.Distance(Target.transform.position, player.transform.position) : 0f;
                    string distance = Target ? $"<color=#00FF00>{targetDistance.ToString("F2")}</color>m" : "~";
                    string distancecolor = "0 1 0 1";
                    if (targetDistance > maxdistance)
                    {
                        distance = Target ? $"<color=#FF0000>{targetDistance.ToString("F2")}</color>m" : "~";
                        distancecolor = "1 0 0 1";
                        isLocked = false;
                    }
                    
                    Instance.DebugLog($"TargetUpdate - Player: {player.displayName}, Target: {shortname}, Distance: {targetDistance:F2}m, Locked: {isLocked}, TimeLocked: {timeLocked:F2}s/{rocketlock}s, Failed: {failed}");
                    
                    // Always update UI every 0.25s to allow dots animation to work, but only send if something changed or it's time for animation update
                    bool needsUpdate = !uiActive || shortname != lastTargetName || distance != lastDistance || isLocked != lastIsLocked || failed != lastLockFailed;
                    // Also update if acquiring (for dots animation) - check every update cycle
                    if (needsUpdate || (!isLocked && !failed))
                    {
                        Instance.DebugLog($"UI UPDATE TRIGGERED - Target: {shortname}, Distance: {distance}, Locked: {isLocked}, Failed: {failed}");
                        Instance.TargetDisplay(player, shortname, distance, distancecolor, isLocked, failed);
                        lastTargetName = shortname;
                        lastDistance = distance;
                        lastIsLocked = isLocked;
                        lastLockFailed = failed;
                        uiActive = true;
                    }
                }
            }
            internal void StopTargetLock(bool keepTarget)
            {
                Instance.DebugLog($"StopTargetLock - Player: {player?.displayName}, KeepTarget: {keepTarget}, HasTarget: {lastTarget != null}");
                
                if (!keepTarget)
                {
                    lastTarget = null;
                    // Reset chance check flags when losing target
                    chancePassedForCurrentTarget = false;
                    targetForChanceCheck = null;
                }
                
                // Always reset lock state
                timeLocked = 0;
                isLocked = false;
                
                // Reset UI cache
                lastTargetName = "";
                lastDistance = "";
                lastIsLocked = false;
                lastLockFailed = false;
                uiActive = false;
                
                if (isAlert)
                {
                    isAlert = false;
                    InvokeHandler.CancelInvoke(this, Alert);
                }
                
                // Always destroy UI when keepTarget is false (not aiming)
                if (!keepTarget && player?.net != null)
                {
                    Instance.DebugLog($"StopTargetLock - Destroying all UI elements for {player.displayName}");
                    // Destroy via CommunityEntity RPC first (more reliable)
                    var communityEntity = CommunityEntity.ServerInstance;
                    if (communityEntity != null)
                    {
                        var destroyData = Pool.Get<List<object>>();
                        destroyData.Add(new { destroyUi = "RGCenterCrosshair" });
                        destroyData.Add(new { destroyUi = "RGCornerTL" });
                        destroyData.Add(new { destroyUi = "RGCornerTR" });
                        destroyData.Add(new { destroyUi = "RGCornerBL" });
                        destroyData.Add(new { destroyUi = "RGCornerBR" });
                        destroyData.Add(new { destroyUi = "RGStatusPanel" });
                        destroyData.Add(new { destroyUi = "RGInfoPanel" });
                        destroyData.Add(new { destroyUi = "RGStatusText" });
                        destroyData.Add(new { destroyUi = "RGTargetName" });
                        destroyData.Add(new { destroyUi = "RGDistance" });
                        communityEntity.ClientRPC(RpcTarget.Player("AddUI", player.net.connection), JsonConvert.SerializeObject(destroyData));
                        Pool.FreeUnmanaged(ref destroyData);
                    }
                    
                    // Also destroy via CuiHelper
                    CuiHelper.DestroyUi(player, RGTargetDisplay);
                    CuiHelper.DestroyUi(player, "RGCenterCrosshair");
                    CuiHelper.DestroyUi(player, "RGCornerTL");
                    CuiHelper.DestroyUi(player, "RGCornerTR");
                    CuiHelper.DestroyUi(player, "RGCornerBL");
                    CuiHelper.DestroyUi(player, "RGCornerBR");
                    CuiHelper.DestroyUi(player, "RGStatusPanel");
                    CuiHelper.DestroyUi(player, "RGStatusText");
                    CuiHelper.DestroyUi(player, "RGInfoPanel");
                    CuiHelper.DestroyUi(player, "RGTargetName");
                    CuiHelper.DestroyUi(player, "RGDistance");
                }
            }
        }
        private class GuidanceSystem : MonoBehaviour
        {
            private ServerProjectile projectile;
            private BaseEntity target;
            private BasePlayer owner;
            private Vector3 targetPosition;
            private float totalDistance;
            private float movingDistance;
            private void Awake()
            {
                projectile = GetComponent<ServerProjectile>();
                enabled = false;
            }
            private void Update()
            {
                if (target == null || target.IsDestroyed) return;
                Vector3 position = target.transform.position + new Vector3(0, target.bounds.center.y / 2, 0);
                if (position != targetPosition)
                {
                    targetPosition = position;
                    float distance = Vector3.Distance(projectile.transform.position, targetPosition);
                    if (distance <= 0.25f)
                    {
                        Destroy(this);
                        return;
                    }
                    Vector3 direction = (targetPosition - projectile.transform.position).normalized;
                    projectile.InitializeVelocity(direction * projectile.speed);
                    float remainingDistance = totalDistance - distance;
                    if (remainingDistance > 0 && totalDistance > 0)
                    {
                        movingDistance = remainingDistance / totalDistance;
                    }
                }
            }
            private void Alert()
            {
                Effect.server.Run("assets/prefabs/locks/keypad/effects/lock.code.unlock.prefab", projectile.transform.position + Vector3.up);
                InvokeHandler.Invoke(this, Alert, 1f - movingDistance);
            }
            public void Initialize(BaseEntity target, BasePlayer owner)
            {
                this.target = target;
                this.owner = owner;
                totalDistance = Vector3.Distance(projectile.transform.position, target.transform.position);
                movingDistance = 0;
                Alert();
                InvokeHandler.Invoke(this, () => enabled = true, 0.5f);
            }
            private void OnDestroy()
            {
                Effect.server.Run("assets/prefabs/tools/c4/effects/c4_explosion.prefab", projectile.transform.position);
            }
        }
        private void TargetDisplay(BasePlayer player, string target, string distance, string distancecolor, bool isLocked, bool lockfailed = false)
        {
            // Get the player's tracking component to access timeLocked for dots animation
            GuidanceSystemPlayer trackingComponent = GetPlayer(player);
            float timeLockedForDots = trackingComponent != null ? trackingComponent.GetTimeLocked() : 0f;
            
            DebugLog($"TargetDisplay CALLED - Player: {player?.displayName}, Target: {target}, Distance: {distance}, Locked: {isLocked}, Failed: {lockfailed}");
            
            if (player == null)
            {
                DebugLog($"TargetDisplay - Player is NULL, aborting");
                return;
            }
            
            if (!permission.UserHasPermission(player.UserIDString, RGSPerm))
            {
                DebugLog($"TargetDisplay - Player {player.displayName} does NOT have permission {RGSPerm}, aborting");
                return;
            }
            
            if (player.net == null)
            {
                DebugLog($"TargetDisplay - Player {player.displayName} has NULL network connection, aborting");
                return;
            }
            
            DebugLog($"TargetDisplay - Destroying existing UI for {player.displayName}");
            // Destroy ALL existing UI elements first to prevent accumulation
            // Destroy via CommunityEntity RPC first (more reliable)
            var communityEntity = CommunityEntity.ServerInstance;
            if (communityEntity != null && player.net?.connection != null)
            {
                var destroyData = Pool.Get<List<object>>();
                destroyData.Add(new { destroyUi = "RGCenterCrosshair" });
                destroyData.Add(new { destroyUi = "RGCornerTL" });
                destroyData.Add(new { destroyUi = "RGCornerTR" });
                destroyData.Add(new { destroyUi = "RGCornerBL" });
                destroyData.Add(new { destroyUi = "RGCornerBR" });
                destroyData.Add(new { destroyUi = "RGStatusPanel" });
                destroyData.Add(new { destroyUi = "RGInfoPanel" });
                destroyData.Add(new { destroyUi = "RGStatusText" });
                destroyData.Add(new { destroyUi = "RGTargetName" });
                destroyData.Add(new { destroyUi = "RGDistance" });
                destroyData.Add(new { destroyUi = RGTargetDisplay });
                communityEntity.ClientRPC(RpcTarget.Player("AddUI", player.net.connection), JsonConvert.SerializeObject(destroyData));
                Pool.FreeUnmanaged(ref destroyData);
            }
            
            // Also destroy via CuiHelper (backup method)
            CuiHelper.DestroyUi(player, RGTargetDisplay);
            CuiHelper.DestroyUi(player, "RGCenterCrosshair");
            CuiHelper.DestroyUi(player, "RGCornerTL");
            CuiHelper.DestroyUi(player, "RGCornerTR");
            CuiHelper.DestroyUi(player, "RGCornerBL");
            CuiHelper.DestroyUi(player, "RGCornerBR");
            CuiHelper.DestroyUi(player, "RGStatusPanel");
            CuiHelper.DestroyUi(player, "RGStatusText");
            CuiHelper.DestroyUi(player, "RGInfoPanel");
            CuiHelper.DestroyUi(player, "RGTargetName");
            CuiHelper.DestroyUi(player, "RGDistance");
            
            // Determine colors based on lock status
            string primaryColor = "1 1 0 1"; // Yellow for acquiring
            string textColor = "1 1 0 1";
            string statusText = $"<color=yellow>ACQUIRING...</color>";
            
            if (isLocked)
            {
                primaryColor = "0 1 0 1"; // Green for locked
                textColor = "0 1 0 1";
                statusText = $"<color=#00FF00>LOCKED</color>";
            }
            else if (lockfailed)
            {
                primaryColor = "1 0 0 1"; // Red for failed
                textColor = "1 0 0 1";
                statusText = $"<color=#FF0000>LOCK FAILED</color>";
            }
            else
            {
                // Animated walking dots for ACQUIRING - progressive dots appear one per second
                // 0s: no dots, 1s: 1 dot, 2s: 2 dots, 3s: 3 dots, then reset
                // Use timeLocked (relative to when tracking started) instead of global Time.time
                float timeForDots = timeLockedForDots;
                int dotCount = Mathf.FloorToInt(timeForDots) % 4; // 0, 1, 2, or 3
                string dots = new string('.', dotCount);
                statusText = $"<color=yellow>ACQUIRING{dots}</color>";
            }
            
            int rocketlockmindistance = (int)config.rocketsettings.distance;
            
            // Create UI using proper Oxide CUI system
            var container = new CuiElementContainer();
            
            // Crosshair image (centered on screen)
            uint crosshairImageId = GetImage(RGCrosshair);
            DebugLog($"TargetDisplay - Crosshair image ID: {crosshairImageId}");
            if (crosshairImageId != 0)
            {
                // Use the crosshair image - centered, much smaller size
                DebugLog($"TargetDisplay - Using crosshair IMAGE (ID: {crosshairImageId}) with color: {primaryColor}");
                
                var crosshairPanel = new CuiPanel
                {
                    Image = { Color = primaryColor, Png = crosshairImageId.ToString() },
                    RectTransform = { AnchorMin = "0.43 0.43", AnchorMax = "0.57 0.57" } // Made larger
                };
                container.Add(crosshairPanel, "Overlay", "RGCenterCrosshair", RGTargetDisplay);
            }
            else
            {
                // Fallback to text-based crosshair if image not loaded
                DebugLog($"TargetDisplay - Crosshair image NOT loaded, using text fallback");
                var centerLabel = new CuiLabel
                {
                    Text = { Text = "•", FontSize = 24, Align = TextAnchor.MiddleCenter, Color = primaryColor, Font = "RobotoCondensed-Bold.ttf" },
                    RectTransform = { AnchorMin = "0.498 0.498", AnchorMax = "0.502 0.502" }
                };
                container.Add(centerLabel, "Overlay", "RGCenterCrosshair", RGTargetDisplay);
                
                // Corner brackets fallback
                var cornerTL = new CuiLabel
                {
                    Text = { Text = "┌", FontSize = 28, Align = TextAnchor.MiddleCenter, Color = primaryColor, Font = "RobotoCondensed-Bold.ttf" },
                    RectTransform = { AnchorMin = "0.32 0.54", AnchorMax = "0.36 0.56" }
                };
                container.Add(cornerTL, "Overlay", "RGCornerTL", RGTargetDisplay);
                
                var cornerTR = new CuiLabel
                {
                    Text = { Text = "┐", FontSize = 28, Align = TextAnchor.MiddleCenter, Color = primaryColor, Font = "RobotoCondensed-Bold.ttf" },
                    RectTransform = { AnchorMin = "0.64 0.54", AnchorMax = "0.68 0.56" }
                };
                container.Add(cornerTR, "Overlay", "RGCornerTR", RGTargetDisplay);
                
                var cornerBL = new CuiLabel
                {
                    Text = { Text = "└", FontSize = 28, Align = TextAnchor.MiddleCenter, Color = primaryColor, Font = "RobotoCondensed-Bold.ttf" },
                    RectTransform = { AnchorMin = "0.32 0.44", AnchorMax = "0.36 0.46" }
                };
                container.Add(cornerBL, "Overlay", "RGCornerBL", RGTargetDisplay);
                
                var cornerBR = new CuiLabel
                {
                    Text = { Text = "┘", FontSize = 28, Align = TextAnchor.MiddleCenter, Color = primaryColor, Font = "RobotoCondensed-Bold.ttf" },
                    RectTransform = { AnchorMin = "0.64 0.44", AnchorMax = "0.68 0.46" }
                };
                container.Add(cornerBR, "Overlay", "RGCornerBR", RGTargetDisplay);
            }
            
            // Status Panel (inside scope view, at bottom)
            var statusPanel = new CuiPanel
            {
                Image = { Color = "0 0 0 0" },
                RectTransform = { AnchorMin = "0.37 0.40", AnchorMax = "0.63 0.48" }
            };
            container.Add(statusPanel, "Overlay", "RGStatusPanel", RGTargetDisplay);
            
            // Status Text (inside scope)
            var statusLabel = new CuiLabel
            {
                Text = { Text = statusText, FontSize = 16, Align = TextAnchor.MiddleCenter, Color = textColor, Font = "RobotoCondensed-Bold.ttf" },
                RectTransform = { AnchorMin = "0 0", AnchorMax = "1 1" }
            };
            container.Add(statusLabel, "RGStatusPanel", "RGStatusText");
            
            // Info Panel (inside scope view, at top) - made taller to accommodate distance text below
            var infoPanel = new CuiPanel
            {
                Image = { Color = "0 0 0 0" },
                RectTransform = { AnchorMin = "0.37 0.50", AnchorMax = "0.63 0.60" }
            };
            container.Add(infoPanel, "Overlay", "RGInfoPanel", RGTargetDisplay);
            
            // Target Name (inside scope) - moved down more
            var targetNameLabel = new CuiLabel
            {
                Text = { Text = $"<color=white>TARGET: {target}</color>", FontSize = 11, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1", Font = "RobotoCondensed-Bold.ttf" },
                RectTransform = { AnchorMin = "0 0.4", AnchorMax = "1 1" }
            };
            container.Add(targetNameLabel, "RGInfoPanel", "RGTargetName");
            
            // Distance (moved outside InfoPanel, positioned below it on Overlay)
            var distanceLabel = new CuiLabel
            {
                Text = { Text = $"RNG: {distance} <size=9>(MAX: {rocketlockmindistance}m)</size>", FontSize = 10, Align = TextAnchor.MiddleCenter, Color = "1 1 1 1", Font = "RobotoCondensed-Bold.ttf" },
                RectTransform = { AnchorMin = "0.37 0.48", AnchorMax = "0.63 0.50" }
            };
            container.Add(distanceLabel, "Overlay", "RGDistance", RGTargetDisplay);
            
            // Send UI to client using proper CuiHelper
            DebugLog($"TargetDisplay - Sending UI to {player.displayName} with {container.Count} elements");
            DebugLog($"TargetDisplay - UI Elements: Crosshair={crosshairImageId != 0}, StatusPanel=Yes, InfoPanel=Yes, Target={target}, Distance={distance}");
            
            string containerJson = container.ToJson();
            DebugLog($"TargetDisplay - UI JSON length: {containerJson.Length} chars");
            if (containerJson.Length > 5000)
            {
                DebugLog($"TargetDisplay - UI JSON (first 500 chars): {containerJson.Substring(0, Math.Min(500, containerJson.Length))}...");
            }
            else
            {
                DebugLog($"TargetDisplay - UI JSON: {containerJson}");
            }
            
            bool uiResult = CuiHelper.AddUi(player, container);
            DebugLog($"TargetDisplay - CuiHelper.AddUi returned: {uiResult} for {player.displayName}");
            
            if (!uiResult)
            {
                DebugLog($"TargetDisplay - FAILED to send UI! Player.net: {player.net != null}, Connection: {player.net?.connection != null}");
                if (player.net == null)
                {
                    DebugLog($"TargetDisplay - ERROR: player.net is NULL!");
                }
                else if (player.net.connection == null)
                {
                    DebugLog($"TargetDisplay - ERROR: player.net.connection is NULL!");
                }
            }
            else
            {
                DebugLog($"TargetDisplay - SUCCESS: UI sent to {player.displayName}");
            }
        }

        // Combat Classes
        void CombatClassChanged(ulong userId, string newClass)
        {
            if (!userId.IsSteamId() || newClass == string.Empty || !config.rocketsettings.useCombatClasses) return;
            var player = FindPlayer(userId);
            if (player == null) return;
            if (newClass == config.rocketsettings.CombatClass)
            {
                if (!permission.UserHasPermission(player.UserIDString, RGSPerm))
                {
                    permission.GrantUserPermission(player.UserIDString, RGSPerm, this);
                }
            }
            else
            {
                permission.RevokeUserPermission(player.UserIDString, RGSPerm);
            }
        }
        #endregion

        #region ImageSystem
        private void LoadImages(bool forcereload = false)
        {
            _isRestart = false;
            _RGImageList = new Dictionary<string, uint>();
            
            // Load crosshair image
            if (RegisterLocalImageKey(RGCrosshair, out uint crosshairId))
            {
                _RGImageList.Add(RGCrosshair, crosshairId);
                Puts($"Successfully loaded crosshair image with ID: {crosshairId}");
            }
            else
            {
                PrintWarning("Failed to load crosshair image. Plugin will use text-based crosshair.");
            }
            
            _isRGReady = true;
        }
        
        private bool RegisterLocalImageKey(string key, out uint id)
        {
            id = 0;
            try
            {
                if (string.IsNullOrEmpty(key)) return false;
                if (_RGImageList.TryGetValue(key, out id) && id != 0) return true;

                // Check RocketGuidanceSystem directory first (where crosshair.png is)
                var imagesDir = System.IO.Path.Combine(Interface.Oxide.DataDirectory, "RocketGuidanceSystem");
                var imagePath = System.IO.Path.Combine(imagesDir, key + ".png");
                
                // If not found, check Images/RocketGuidance directory
                if (!System.IO.File.Exists(imagePath))
                {
                    imagesDir = System.IO.Path.Combine(Interface.Oxide.DataDirectory, "Images", "RocketGuidance");
                    imagePath = System.IO.Path.Combine(imagesDir, key + ".png");
                }
                
                
                var root = Oxide.Core.OxideMod.ResolveServerRoot();
                var hi = System.IO.Path.Combine(root, "HarmonyImages", "RocketGuidanceSystem", key + ".png");
                if (!System.IO.File.Exists(imagePath) && System.IO.File.Exists(hi)) imagePath = hi;
                if (!System.IO.File.Exists(imagePath)) return false;

                var bytes = System.IO.File.ReadAllBytes(imagePath);
                var ownerIdNullable = CommunityEntity.ServerInstance?.net?.ID;
                var owner = ownerIdNullable ?? default(NetworkableId);
                if (owner == default(NetworkableId)) return false;

                id = FileStorage.server.Store(bytes, FileStorage.Type.png, owner);
                if (id == 0) return false;

                return true;
            }
            catch (Exception ex)
            {
                PrintWarning($"Failed to load image '{key}': {ex.Message}");
                id = 0;
                return false;
            }
        }
        
        
        private uint GetImage(string fileName)
        {
            if (_RGImageList.TryGetValue(fileName, out var imageId))
                return imageId;
            return 0;
        }
        #endregion

        #region UI Constants
        private const string RGTargetDisplay = "RGTargetDisplay";
        private const string RGTargetData = "RGTargetData";
        // Images
        private const string RGCrosshair = "crosshair";
        #endregion

        #region UI
        // UI methods removed - now using CommunityEntity UI system
        #endregion

        #region Lang
        protected override void LoadDefaultMessages()
        {
            lang.RegisterMessages(new Dictionary<string, string>
            {
                ["targetname"] = "Target",
                ["targetdistance"] = "Distance",
                ["targetdistancemax"] = "max",
                ["lockpending"] = "PENDING (HOLD)",
                ["lockfailed"] = "FAILED (HOLD)",
                ["locked"] = "LOCKED (FIRE)",
                ["lock"] = "Lock",
            }, this);
        }
        private string RGTLang(string key, string id = null, params object[] args) => string.Format(lang.GetMessage(key, this, id), args);
        #endregion
    }
} 