<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>InstantBarrel</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <RootNamespace>InstantBarrel</RootNamespace>
    <Description>Harmony mod: Makes barrels and road signs 1 HP and instantly spawns loot in player inventory. Requires companion Oxide plugin for permission.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Rust.Harmony">
      <HintPath>$(RustManaged)\Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(RustManaged)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RustManaged)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RustManaged)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(RustManaged)\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>$(RustManaged)\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
