<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MapVoter</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <LangVersion>12.0</LangVersion>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\ConsoleIndexCompat.cs" Link="ConsoleIndexCompat.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>$(RustManaged)\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime">
      <HintPath>$(RustManaged)\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>$(RustManaged)\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(RustManaged)\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe">
      <HintPath>$(RustManaged)\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <HintPath>$(RustManaged)\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(RustManaged)\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>$(RustManaged)\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Drawing">
      <HintPath>$(RustManaged)\System.Drawing.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Harmony">
      <HintPath>$(RustManaged)\Rust.Harmony.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(RustManaged)\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RustManaged)\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(RustManaged)\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>$(RustManaged)\Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>$(RustManaged)\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>$(RustManaged)\Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>$(RustManaged)\Facepunch.Console.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>$(RustManaged)\Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RustManaged)\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(RustManaged)\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(RustManaged)\UnityEngine.UnityWebRequestModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
